### ISSUE TITLE
Support for PhantomJS

### ISSUE THREAD

**Issue by pgrunewald** [datakurre/robotrecorder_vagrant#1]
Hello Asko,

at first I want to say: Great job you did there! What do you think, is necessary to supporting phantomJS? Judging from manifests/default.pp, it's pretty hard job pulling all dependencies together at it is now.

regards, Paul

**Comment by pgrunewald** [comment]
Also considering using the box: ubuntu/trusty32 (url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box)

**Comment by datakurre** [comment]
@pgrunewald I'm sorry, but these are not possible.

The recording is based on vnc2flv, which requires a real browser window in a VNC session.

Debian is required to support recording audio from the browser (based on ALSA with snd-aloop *). I tried Ubuntu, but it either did not have snd-aloop or ALSA. I don't remember exactly. And I have no idea, how to route audio in a headless Ubuntu in the same way.

*) https://github.com/datakurre/robotrecorder_vagrant/blob/master/manifests/default.pp#L103
